const seats = [
  {
    "id": 1,
    "rowNumber": 1,
    "seatNumber": 1,
    "auditoriumId": 1
  },
  {
    "id": 2,
    "rowNumber": 1,
    "seatNumber": 2,
    "auditoriumId": 1
  },
  {
    "id": 3,
    "rowNumber": 1,
    "seatNumber": 3,
    "auditoriumId": 1
  },
  {
    "id": 4,
    "rowNumber": 1,
    "seatNumber": 4,
    "auditoriumId": 1
  },
  {
    "id": 5,
    "rowNumber": 1,
    "seatNumber": 5,
    "auditoriumId": 1
  },
  {
    "id": 6,
    "rowNumber": 1,
    "seatNumber": 6,
    "auditoriumId": 1
  },
  {
    "id": 7,
    "rowNumber": 1,
    "seatNumber": 7,
    "auditoriumId": 1
  },
  {
    "id": 8,
    "rowNumber": 1,
    "seatNumber": 8,
    "auditoriumId": 1
  },
  {
    "id": 9,
    "rowNumber": 2,
    "seatNumber": 9,
    "auditoriumId": 1
  },
  {
    "id": 10,
    "rowNumber": 2,
    "seatNumber": 10,
    "auditoriumId": 1
  },
  {
    "id": 11,
    "rowNumber": 2,
    "seatNumber": 11,
    "auditoriumId": 1
  },
  {
    "id": 12,
    "rowNumber": 2,
    "seatNumber": 12,
    "auditoriumId": 1
  },
  {
    "id": 13,
    "rowNumber": 2,
    "seatNumber": 13,
    "auditoriumId": 1
  },
  {
    "id": 14,
    "rowNumber": 2,
    "seatNumber": 14,
    "auditoriumId": 1
  },
  {
    "id": 15,
    "rowNumber": 2,
    "seatNumber": 15,
    "auditoriumId": 1
  },
  {
    "id": 16,
    "rowNumber": 2,
    "seatNumber": 16,
    "auditoriumId": 1
  },
  {
    "id": 17,
    "rowNumber": 2,
    "seatNumber": 17,
    "auditoriumId": 1
  },
  {
    "id": 18,
    "rowNumber": 3,
    "seatNumber": 18,
    "auditoriumId": 1
  },
  {
    "id": 19,
    "rowNumber": 3,
    "seatNumber": 19,
    "auditoriumId": 1
  },
  {
    "id": 20,
    "rowNumber": 3,
    "seatNumber": 20,
    "auditoriumId": 1
  },
  {
    "id": 21,
    "rowNumber": 3,
    "seatNumber": 21,
    "auditoriumId": 1
  },
  {
    "id": 22,
    "rowNumber": 3,
    "seatNumber": 22,
    "auditoriumId": 1
  },
  {
    "id": 23,
    "rowNumber": 3,
    "seatNumber": 23,
    "auditoriumId": 1
  },
  {
    "id": 24,
    "rowNumber": 3,
    "seatNumber": 24,
    "auditoriumId": 1
  },
  {
    "id": 25,
    "rowNumber": 3,
    "seatNumber": 25,
    "auditoriumId": 1
  },
  {
    "id": 26,
    "rowNumber": 3,
    "seatNumber": 26,
    "auditoriumId": 1
  },
  {
    "id": 27,
    "rowNumber": 3,
    "seatNumber": 27,
    "auditoriumId": 1
  },
  {
    "id": 28,
    "rowNumber": 4,
    "seatNumber": 28,
    "auditoriumId": 1
  },
  {
    "id": 29,
    "rowNumber": 4,
    "seatNumber": 29,
    "auditoriumId": 1
  },
  {
    "id": 30,
    "rowNumber": 4,
    "seatNumber": 30,
    "auditoriumId": 1
  },
  {
    "id": 31,
    "rowNumber": 4,
    "seatNumber": 31,
    "auditoriumId": 1
  },
  {
    "id": 32,
    "rowNumber": 4,
    "seatNumber": 32,
    "auditoriumId": 1
  },
  {
    "id": 33,
    "rowNumber": 4,
    "seatNumber": 33,
    "auditoriumId": 1
  },
  {
    "id": 34,
    "rowNumber": 4,
    "seatNumber": 34,
    "auditoriumId": 1
  },
  {
    "id": 35,
    "rowNumber": 4,
    "seatNumber": 35,
    "auditoriumId": 1
  },
  {
    "id": 36,
    "rowNumber": 4,
    "seatNumber": 36,
    "auditoriumId": 1
  },
  {
    "id": 37,
    "rowNumber": 4,
    "seatNumber": 37,
    "auditoriumId": 1
  },
  {
    "id": 38,
    "rowNumber": 5,
    "seatNumber": 38,
    "auditoriumId": 1
  },
  {
    "id": 39,
    "rowNumber": 5,
    "seatNumber": 39,
    "auditoriumId": 1
  },
  {
    "id": 40,
    "rowNumber": 5,
    "seatNumber": 40,
    "auditoriumId": 1
  },
  {
    "id": 41,
    "rowNumber": 5,
    "seatNumber": 41,
    "auditoriumId": 1
  },
  {
    "id": 42,
    "rowNumber": 5,
    "seatNumber": 42,
    "auditoriumId": 1
  },
  {
    "id": 43,
    "rowNumber": 5,
    "seatNumber": 43,
    "auditoriumId": 1
  },
  {
    "id": 44,
    "rowNumber": 5,
    "seatNumber": 44,
    "auditoriumId": 1
  },
  {
    "id": 45,
    "rowNumber": 5,
    "seatNumber": 45,
    "auditoriumId": 1
  },
  {
    "id": 46,
    "rowNumber": 5,
    "seatNumber": 46,
    "auditoriumId": 1
  },
  {
    "id": 47,
    "rowNumber": 5,
    "seatNumber": 47,
    "auditoriumId": 1
  },
  {
    "id": 48,
    "rowNumber": 6,
    "seatNumber": 48,
    "auditoriumId": 1
  },
  {
    "id": 49,
    "rowNumber": 6,
    "seatNumber": 49,
    "auditoriumId": 1
  },
  {
    "id": 50,
    "rowNumber": 6,
    "seatNumber": 50,
    "auditoriumId": 1
  },
  {
    "id": 51,
    "rowNumber": 6,
    "seatNumber": 51,
    "auditoriumId": 1
  },
  {
    "id": 52,
    "rowNumber": 6,
    "seatNumber": 52,
    "auditoriumId": 1
  },
  {
    "id": 53,
    "rowNumber": 6,
    "seatNumber": 53,
    "auditoriumId": 1
  },
  {
    "id": 54,
    "rowNumber": 6,
    "seatNumber": 54,
    "auditoriumId": 1
  },
  {
    "id": 55,
    "rowNumber": 6,
    "seatNumber": 55,
    "auditoriumId": 1
  },
  {
    "id": 56,
    "rowNumber": 6,
    "seatNumber": 56,
    "auditoriumId": 1
  },
  {
    "id": 57,
    "rowNumber": 6,
    "seatNumber": 57,
    "auditoriumId": 1
  },
  {
    "id": 58,
    "rowNumber": 7,
    "seatNumber": 58,
    "auditoriumId": 1
  },
  {
    "id": 59,
    "rowNumber": 7,
    "seatNumber": 59,
    "auditoriumId": 1
  },
  {
    "id": 60,
    "rowNumber": 7,
    "seatNumber": 60,
    "auditoriumId": 1
  },
  {
    "id": 61,
    "rowNumber": 7,
    "seatNumber": 61,
    "auditoriumId": 1
  },
  {
    "id": 62,
    "rowNumber": 7,
    "seatNumber": 62,
    "auditoriumId": 1
  },
  {
    "id": 63,
    "rowNumber": 7,
    "seatNumber": 63,
    "auditoriumId": 1
  },
  {
    "id": 64,
    "rowNumber": 7,
    "seatNumber": 64,
    "auditoriumId": 1
  },
  {
    "id": 65,
    "rowNumber": 7,
    "seatNumber": 65,
    "auditoriumId": 1
  },
  {
    "id": 66,
    "rowNumber": 7,
    "seatNumber": 66,
    "auditoriumId": 1
  },
  {
    "id": 67,
    "rowNumber": 7,
    "seatNumber": 67,
    "auditoriumId": 1
  },
  {
    "id": 68,
    "rowNumber": 7,
    "seatNumber": 68,
    "auditoriumId": 1
  },
  {
    "id": 69,
    "rowNumber": 7,
    "seatNumber": 69,
    "auditoriumId": 1
  },
  {
    "id": 70,
    "rowNumber": 8,
    "seatNumber": 70,
    "auditoriumId": 1
  },
  {
    "id": 71,
    "rowNumber": 8,
    "seatNumber": 71,
    "auditoriumId": 1
  },
  {
    "id": 72,
    "rowNumber": 8,
    "seatNumber": 72,
    "auditoriumId": 1
  },
  {
    "id": 73,
    "rowNumber": 8,
    "seatNumber": 73,
    "auditoriumId": 1
  },
  {
    "id": 74,
    "rowNumber": 8,
    "seatNumber": 74,
    "auditoriumId": 1
  },
  {
    "id": 75,
    "rowNumber": 8,
    "seatNumber": 75,
    "auditoriumId": 1
  },
  {
    "id": 76,
    "rowNumber": 8,
    "seatNumber": 76,
    "auditoriumId": 1
  },
  {
    "id": 77,
    "rowNumber": 8,
    "seatNumber": 77,
    "auditoriumId": 1
  },
  {
    "id": 78,
    "rowNumber": 8,
    "seatNumber": 78,
    "auditoriumId": 1
  },
  {
    "id": 79,
    "rowNumber": 8,
    "seatNumber": 79,
    "auditoriumId": 1
  },
  {
    "id": 80,
    "rowNumber": 8,
    "seatNumber": 80,
    "auditoriumId": 1
  },
  {
    "id": 81,
    "rowNumber": 8,
    "seatNumber": 81,
    "auditoriumId": 1
  }
]
export default seats;